// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/bicycle": {
            "get": {
                "description": "Gets all the bicycle data from database",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "BicyleData"
                ],
                "summary": "Gets all bicycle data from database",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.BicycleData"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/bicycle/config": {
            "get": {
                "description": "Gets the current config from database",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ConfigData"
                ],
                "summary": "Gets the current config from database",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ConfigData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/bicycle/speed": {
            "get": {
                "description": "Computes the current bicycle speed from the latest data in firebase",
                "tags": [
                    "BicyleSpeed"
                ],
                "summary": "Computes the current bicycle speed from database",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "int"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.BicycleData": {
            "type": "object",
            "properties": {
                "revolutions": {
                    "type": "integer",
                    "example": 10
                },
                "rpm": {
                    "type": "integer",
                    "example": 200
                },
                "time": {
                    "type": "string",
                    "example": "2021-10-26T22:17:36Z"
                }
            }
        },
        "models.ConfigData": {
            "type": "object",
            "properties": {
                "radius_in_cm": {
                    "type": "number",
                    "example": 30
                },
                "target_km": {
                    "type": "integer",
                    "example": 150
                }
            }
        },
        "models.ErrorResponse": {
            "type": "object",
            "properties": {
                "error_code": {
                    "type": "string",
                    "example": "UnprocessableEntity"
                },
                "message": {
                    "type": "string",
                    "example": "Malformed body"
                },
                "status_code": {
                    "type": "integer",
                    "example": 422
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "0.1.0",
	Host:        "",
	BasePath:    "/v1",
	Schemes:     []string{},
	Title:       "bicycle API",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register("swagger", &s{})
}
